image: google/cloud-sdk:alpine
stages:
  - deploy

default:
  before_script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - gcloud auth activate-service-account --key-file .secure_files/maximal-radius-375114-f09823b3e627.json
  after_script:
    - rm -rf .secret_files

deploy_application:
  stage: deploy
  only:
    - main
  script:
    - gcloud app deploy app.yaml --quiet --project $PROJECT_ID

deploy_invoicing_function:
  stage: deploy
  only:
    - main
  script:
    - cd invoicing-function
    - gcloud functions deploy invoicing-function  --project $PROJECT_ID --quiet --max-instances 1 --entry-point $(cat functionMainClass) --region europe-west3 --runtime java17 --trigger-http --memory 512MB

deploy_bi_function:
  stage: deploy
  only:
    - main
  script:
    - cd bi-function
    - gcloud functions deploy bi-function --project $PROJECT_ID --quiet --max-instances 1 --entry-point $(cat functionMainClass) --region europe-west3 --runtime java17 --trigger-http --memory 512MB