spring:
    datasource:
        username: postgres
        password: ${DB_PASSWD}
        url: jdbc:postgresql://34.141.11.95:5432/prost
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: update
    thymeleaf:
        cache: true
server:
    servlet:
        session:
            cookie:
                http-only: true
                secure: true