spring:
    datasource:
        username: postgres
        password: ${DB_PASSWD}
        url: jdbc:postgresql://172.17.0.1:5678/prost
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: update
    thymeleaf:
        cache: true

server:
    servlet:
        session:
            cookie:
                http-only: true
                secure: true