spring:
    h2:
        console:
            enabled: false
    datasource:
        username: prostadmin
        password: strongpassword
        url: jdbc:h2:mem:prost
        driverClassName: org.h2.Driver
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
    thymeleaf:
        cache: true

server:
    servlet:
        session:
            cookie:
                http-only: true
                secure: true